import { IContactInformationAPIResult } from "./AccountTypes";

export const SPOOFED_GET_Contact: IContactInformationAPIResult = JSON.parse(
  JSON.stringify({
    results: {
      Id: "a33eb962-1b1d-e811-80e6-000d3a7075d4",
      IsLoggedIn: true,
      IsGuest: false,
      IsPartner: false,
      Security: {
        IsAdmin: false,
        SecurityRoles: null,
        SecurityFlags: null,
        SecurityAuthority: null,
      },
      Address: {
        Id: "8cf1ea5c-7159-42ab-8877-6d916988968a",
        CustomerId: null,
        FirstName: "lodee",
        LastName: "joseph",
        IsPrimary: true,
        IsDefaultBilling: false,
        IsDefaultShipping: false,
        IsSelected: false,
        City: "Nashville",
        StateDetail: {
          Name: "Tennessee",
          Iso2Code: "TN",
          Country: null,
          IsSelected: false,
        },
        DoNotMail: false,
        State: "Tennessee",
        CountryDetail: {
          Name: "UNITED STATES",
          Iso2Code: "US",
          Iso3Code: "USA",
          IsSelected: false,
          CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
          Id: "752029fe-6ea9-df11-9532-005056954cab",
        },
        Country: "UNITED STATES",
        Summary:
          "116 Rep. John Lewis Way North, , Nashville, Tennessee, 37219, UNITED STATES",
        Latitude: 0.0,
        Longitude: 0.0,
        Line1: "116 Rep. John Lewis Way North",
        Line2: null,
        Person: null,
        Name: null,
        PostalCode: "37219",
        HasBasicData: true,
      },
      DefaultBillingAddress: {
        Id: "d43f7264-8ba7-4dd2-97ca-2f4353cca170",
        CustomerId: null,
        FirstName: "lodee",
        LastName: "joseph",
        IsPrimary: true,
        IsDefaultBilling: false,
        IsDefaultShipping: false,
        IsSelected: false,
        City: "Nashville",
        StateDetail: {
          Name: "Tennessee",
          Iso2Code: "TN",
          Country: null,
          IsSelected: false,
        },
        DoNotMail: false,
        State: "Tennessee",
        CountryDetail: {
          Name: "UNITED STATES",
          Iso2Code: "US",
          Iso3Code: "USA",
          IsSelected: false,
          CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
          Id: "752029fe-6ea9-df11-9532-005056954cab",
        },
        Country: "UNITED STATES",
        Summary:
          "116 Rep. John Lewis Way North, , Nashville, Tennessee, 37219, UNITED STATES",
        Latitude: 0.0,
        Longitude: 0.0,
        Line1: "116 Rep. John Lewis Way North",
        Line2: null,
        Person: null,
        Name: null,
        PostalCode: "37219",
        HasBasicData: true,
      },
      DefaultShippingAddress: {
        Id: "5ce3083e-d721-4344-b6c6-06ee059152a4",
        CustomerId: null,
        FirstName: "lodee",
        LastName: "joseph",
        IsPrimary: true,
        IsDefaultBilling: false,
        IsDefaultShipping: false,
        IsSelected: false,
        City: "Nashville",
        StateDetail: {
          Name: "Tennessee",
          Iso2Code: "TN",
          Country: null,
          IsSelected: false,
        },
        DoNotMail: false,
        State: "Tennessee",
        CountryDetail: {
          Name: "UNITED STATES",
          Iso2Code: "US",
          Iso3Code: "USA",
          IsSelected: false,
          CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
          Id: "752029fe-6ea9-df11-9532-005056954cab",
        },
        Country: "UNITED STATES",
        Summary:
          "116 Rep. John Lewis Way North, , Nashville, Tennessee, 37219, UNITED STATES",
        Latitude: 0.0,
        Longitude: 0.0,
        Line1: "116 Rep. John Lewis Way North",
        Line2: null,
        Person: null,
        Name: null,
        PostalCode: "37219",
        HasBasicData: true,
      },
      BirthDate: null,
      DoNotEmail: false,
      DoNotPhone: false,
      DoNotCallMobile: null,
      AllowSMS: null,
      DoNotPostalMail: false,
      PrimaryEmailAddress: "test@joelosteen.com",
      FirstName: "lodee",
      LastName: "joseph",
      FullName: "lodee joseph",
      Gender: 3,
      Acno: "C009428914",
      Church: null,
      Discount: 0.0,
      PriceLevelId: "5f7fcdb8-a87a-e611-80c9-000d3a700f55",
      Facebook: null,
      Instagram: null,
      TaxExempt: false,
      Twitter: null,
      LastLogin: "2023-10-24T19:38:31Z",
      IsPrivate: false,
      PhoneNumber: null,
      MobilePhoneNumber: null,
      SiteCode: "JOM",
      Sourcecode: "1800JIAD",
      CreatedOn: "2018-03-01T06:40:10Z",
      LastDonationAmount: 0.0,
      HighestDonationAmount: 0.0,
      AverageDonationAmount: 0.0,
      GiftAskLow: 10.0,
      GiftAskMid: 15.0,
      GiftAskHigh: 25.0,
      JOMMobile: null,
      LWCMobile: null,
      DonorFrequency: "",
      DonorType: "",
      GivingHistory: [],
      AuthToken: null,
      RedirectUrl: null,
      DefaultCurrency: null,
      AdminChurches: null,
    },
  })
);

