import { IEmailSubscriptionsAPIResult } from "./EmailSubscriptionsTypes";

export const SPOOFED_GET_EmailSubscriptions_EMAIL_1: IEmailSubscriptionsAPIResult =
  JSON.parse(
    JSON.stringify({
      results: [
        {
          ListName: "jom",
          IsSubscribed: true,
          EmailAddress: "test@joelosteen.com",
          OptedIn: null,
          OptedOut: null,
          Status: "Sub",
          Description: "JOM",
          ListTitle: "Joel Osteen Ministries General",
          Organization: "Joel Osteen Ministries",
          IsInterest: false,
          Site: null,
        },
        {
          ListName: "todaysword",
          IsSubscribed: false,
          EmailAddress: "test@joelosteen.com",
          OptedIn: "2017-01-21T00:00:00",
          OptedOut: null,
          Status: "Unsub",
          Description: "DD",
          ListTitle: "Today's Word Daily Devotional",
          Organization: "Joel Osteen Ministries",
          IsInterest: false,
          Site: null,
        },
        {
          ListName: "lch",
          IsSubscribed: false,
          EmailAddress: "test@joelosteen.com",
          OptedIn: "2017-01-21T00:00:00",
          OptedOut: null,
          Status: "Unsub",
          Description: "LCH",
          ListTitle: "Lakewood Church General",
          Organization: "Lakewood Church",
          IsInterest: false,
          Site: null,
        },
        {
          ListName: "thisweek",
          IsSubscribed: false,
          EmailAddress: "test@joelosteen.com",
          OptedIn: "2017-01-21T00:00:00",
          OptedOut: null,
          Status: "Unsub",
          Description: "ThisWeek",
          ListTitle: "This Week at Lakewood",
          Organization: "Lakewood Church",
          IsInterest: false,
          Site: null,
        },
        {
          ListName: "lisacomes",
          IsSubscribed: false,
          EmailAddress: "test@joelosteen.com",
          OptedIn: "2017-01-21T00:00:00",
          OptedOut: null,
          Status: "Unsub",
          Description: "Lisa",
          ListTitle: "Lisa Comes Inspirational Emails",
          Organization: "Joel Osteen Ministries",
          IsInterest: false,
          Site: null,
        },
        {
          ListName: "spanish",
          IsSubscribed: false,
          EmailAddress: "test@joelosteen.com",
          OptedIn: "2017-01-21T00:00:00",
          OptedOut: null,
          Status: "Unsub",
          Description: "Iglesia",
          ListTitle: "Lista general de",
          Organization: "Iglesia Lakewood",
          IsInterest: false,
          Site: null,
        },
        {
          ListName: "esta_semana",
          IsSubscribed: false,
          EmailAddress: "test@joelosteen.com",
          OptedIn: "2017-01-21T00:00:00",
          OptedOut: null,
          Status: "Unsub",
          Description: "Esta_Semana",
          ListTitle: "Esta Semana en Lakewood",
          Organization: "Iglesia Lakewood",
          IsInterest: false,
          Site: null,
        },
        {
          ListName: "Kidslife",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Kidslife",
          ListTitle: "Kidslife",
          Organization: "Lakewood Church",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "Life Groups",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Life Groups",
          ListTitle: "Life Groups",
          Organization: "Lakewood Church",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "Middle School",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Middle School",
          ListTitle: "Middle School",
          Organization: "Lakewood Church",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "High School",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "High School",
          ListTitle: "High School",
          Organization: "Lakewood Church",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "Young Adults",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Young Adults",
          ListTitle: "Young Adults",
          Organization: "Lakewood Church",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "Men's Ministry",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Men's Ministry",
          ListTitle: "Men's Ministry",
          Organization: "Lakewood Church",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "Women's Ministry",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Women's Ministry",
          ListTitle: "Women's Ministry",
          Organization: "Lakewood Church",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "Young at Heart",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Young at Heart",
          ListTitle: "Young at Heart",
          Organization: "Lakewood Church",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "Marriage and Parenting",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Marriage and Parenting",
          ListTitle: "Marriage and Parenting",
          Organization: "Lakewood Church",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "Singles",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Singles",
          ListTitle: "Singles",
          Organization: "Lakewood Church",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "Christian Education",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Christian Education",
          ListTitle: "Christian Education",
          Organization: "Lakewood Church",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "Planned Giving",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Planned Giving",
          ListTitle: "Planned Giving",
          Organization: "Lakewood Church",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "Grupos con Vida",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Grupos con Vida",
          ListTitle: "Grupos con Vida",
          Organization: "Iglesia Lakewood",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "Ninos con Vida",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Ninos con Vida",
          ListTitle: "Niños con Vida",
          Organization: "Iglesia Lakewood",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "Conexion Jr High",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Conexion Jr High",
          ListTitle: "Conexión Jr High",
          Organization: "Iglesia Lakewood",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "Conexion HS",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Conexion HS",
          ListTitle: "Conexión HS",
          Organization: "Iglesia Lakewood",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "Conexion 19 Plus",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Conexion 19 Plus",
          ListTitle: "Conexión 19+",
          Organization: "Iglesia Lakewood",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "Ministerio de Hombre",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Ministerio de Hombre",
          ListTitle: "Ministerio de Hombre",
          Organization: "Iglesia Lakewood",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "Ministerio de Mujeres",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Ministerio de Mujeres",
          ListTitle: "Ministerio de Mujeres",
          Organization: "Iglesia Lakewood",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "Matrimonios con Vida",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Matrimonios con Vida",
          ListTitle: "Matrimonios con Vida",
          Organization: "Iglesia Lakewood",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "Celebremos la Recuperacion",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Celebremos la Recuperacion",
          ListTitle: "Celebremos la Recuperación",
          Organization: "Iglesia Lakewood",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "Rumbo Norte",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Rumbo Norte",
          ListTitle: "Rumbo Norte",
          Organization: "Iglesia Lakewood",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "Nuevos Convertidos",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Nuevos Convertidos",
          ListTitle: "Nuevos Convertidos",
          Organization: "Iglesia Lakewood",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "Emprendedores",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Emprendedores",
          ListTitle: "Emprendedores",
          Organization: "Iglesia Lakewood",
          IsInterest: true,
          Site: null,
        },
      ],
    })
  );

export const SPOOFED_GET_EmailSubscriptions_EMAIL_2: IEmailSubscriptionsAPIResult =
  JSON.parse(
    JSON.stringify({
      results: [
        {
          ListName: "Kidslife",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Kidslife",
          ListTitle: "Kidslife",
          Organization: "Lakewood Church",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "Life Groups",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Life Groups",
          ListTitle: "Life Groups",
          Organization: "Lakewood Church",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "Middle School",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Middle School",
          ListTitle: "Middle School",
          Organization: "Lakewood Church",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "High School",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "High School",
          ListTitle: "High School",
          Organization: "Lakewood Church",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "Young Adults",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Young Adults",
          ListTitle: "Young Adults",
          Organization: "Lakewood Church",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "Men's Ministry",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Men's Ministry",
          ListTitle: "Men's Ministry",
          Organization: "Lakewood Church",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "Women's Ministry",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Women's Ministry",
          ListTitle: "Women's Ministry",
          Organization: "Lakewood Church",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "Young at Heart",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Young at Heart",
          ListTitle: "Young at Heart",
          Organization: "Lakewood Church",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "Marriage and Parenting",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Marriage and Parenting",
          ListTitle: "Marriage and Parenting",
          Organization: "Lakewood Church",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "Singles",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Singles",
          ListTitle: "Singles",
          Organization: "Lakewood Church",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "Christian Education",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Christian Education",
          ListTitle: "Christian Education",
          Organization: "Lakewood Church",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "Planned Giving",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Planned Giving",
          ListTitle: "Planned Giving",
          Organization: "Lakewood Church",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "Grupos con Vida",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Grupos con Vida",
          ListTitle: "Grupos con Vida",
          Organization: "Iglesia Lakewood",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "Ninos con Vida",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Ninos con Vida",
          ListTitle: "Niños con Vida",
          Organization: "Iglesia Lakewood",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "Conexion Jr High",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Conexion Jr High",
          ListTitle: "Conexión Jr High",
          Organization: "Iglesia Lakewood",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "Conexion HS",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Conexion HS",
          ListTitle: "Conexión HS",
          Organization: "Iglesia Lakewood",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "Conexion 19 Plus",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Conexion 19 Plus",
          ListTitle: "Conexión 19+",
          Organization: "Iglesia Lakewood",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "Ministerio de Hombre",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Ministerio de Hombre",
          ListTitle: "Ministerio de Hombre",
          Organization: "Iglesia Lakewood",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "Ministerio de Mujeres",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Ministerio de Mujeres",
          ListTitle: "Ministerio de Mujeres",
          Organization: "Iglesia Lakewood",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "Matrimonios con Vida",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Matrimonios con Vida",
          ListTitle: "Matrimonios con Vida",
          Organization: "Iglesia Lakewood",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "Celebremos la Recuperacion",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Celebremos la Recuperacion",
          ListTitle: "Celebremos la Recuperación",
          Organization: "Iglesia Lakewood",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "Rumbo Norte",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Rumbo Norte",
          ListTitle: "Rumbo Norte",
          Organization: "Iglesia Lakewood",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "Nuevos Convertidos",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Nuevos Convertidos",
          ListTitle: "Nuevos Convertidos",
          Organization: "Iglesia Lakewood",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "Emprendedores",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Emprendedores",
          ListTitle: "Emprendedores",
          Organization: "Iglesia Lakewood",
          IsInterest: true,
          Site: null,
        },
      ],
    })
  );

export const SPOOFED_GET_EmailSubscriptions_EMAIL_3: IEmailSubscriptionsAPIResult =
  JSON.parse(
    JSON.stringify({
      results: [
        {
          ListName: "jom",
          IsSubscribed: true,
          EmailAddress: "ven-dobrien@lakewood.cc",
          OptedIn: null,
          OptedOut: null,
          Status: "Sub",
          Description: "JOM",
          ListTitle: "Joel Osteen Ministries General",
          Organization: "Joel Osteen Ministries",
          IsInterest: false,
          Site: null,
        },
        {
          ListName: "todaysword",
          IsSubscribed: false,
          EmailAddress: "ven-dobrien@lakewood.cc",
          OptedIn: "2017-01-21T00:00:00",
          OptedOut: null,
          Status: "Unsub",
          Description: "DD",
          ListTitle: "Today's Word Daily Devotional",
          Organization: "Joel Osteen Ministries",
          IsInterest: false,
          Site: null,
        },
        {
          ListName: "lch",
          IsSubscribed: false,
          EmailAddress: "ven-dobrien@lakewood.cc",
          OptedIn: "2017-01-21T00:00:00",
          OptedOut: null,
          Status: "Unsub",
          Description: "LCH",
          ListTitle: "Lakewood Church General",
          Organization: "Lakewood Church",
          IsInterest: false,
          Site: null,
        },
        {
          ListName: "thisweek",
          IsSubscribed: false,
          EmailAddress: "ven-dobrien@lakewood.cc",
          OptedIn: "2017-01-21T00:00:00",
          OptedOut: null,
          Status: "Unsub",
          Description: "ThisWeek",
          ListTitle: "This Week at Lakewood",
          Organization: "Lakewood Church",
          IsInterest: false,
          Site: null,
        },
        {
          ListName: "lisacomes",
          IsSubscribed: false,
          EmailAddress: "ven-dobrien@lakewood.cc",
          OptedIn: "2017-01-21T00:00:00",
          OptedOut: null,
          Status: "Unsub",
          Description: "Lisa",
          ListTitle: "Lisa Comes Inspirational Emails",
          Organization: "Joel Osteen Ministries",
          IsInterest: false,
          Site: null,
        },
        {
          ListName: "spanish",
          IsSubscribed: false,
          EmailAddress: "ven-dobrien@lakewood.cc",
          OptedIn: "2017-01-21T00:00:00",
          OptedOut: null,
          Status: "Unsub",
          Description: "Iglesia",
          ListTitle: "Lista general de",
          Organization: "Iglesia Lakewood",
          IsInterest: false,
          Site: null,
        },
        {
          ListName: "esta_semana",
          IsSubscribed: false,
          EmailAddress: "ven-dobrien@lakewood.cc",
          OptedIn: "2017-01-21T00:00:00",
          OptedOut: null,
          Status: "Unsub",
          Description: "Esta_Semana",
          ListTitle: "Esta Semana en Lakewood",
          Organization: "Iglesia Lakewood",
          IsInterest: false,
          Site: null,
        },
        {
          ListName: "Kidslife",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Kidslife",
          ListTitle: "Kidslife",
          Organization: "Lakewood Church",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "Life Groups",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Life Groups",
          ListTitle: "Life Groups",
          Organization: "Lakewood Church",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "Middle School",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Middle School",
          ListTitle: "Middle School",
          Organization: "Lakewood Church",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "High School",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "High School",
          ListTitle: "High School",
          Organization: "Lakewood Church",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "Young Adults",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Young Adults",
          ListTitle: "Young Adults",
          Organization: "Lakewood Church",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "Men's Ministry",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Men's Ministry",
          ListTitle: "Men's Ministry",
          Organization: "Lakewood Church",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "Women's Ministry",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Women's Ministry",
          ListTitle: "Women's Ministry",
          Organization: "Lakewood Church",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "Young at Heart",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Young at Heart",
          ListTitle: "Young at Heart",
          Organization: "Lakewood Church",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "Marriage and Parenting",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Marriage and Parenting",
          ListTitle: "Marriage and Parenting",
          Organization: "Lakewood Church",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "Singles",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Singles",
          ListTitle: "Singles",
          Organization: "Lakewood Church",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "Christian Education",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Christian Education",
          ListTitle: "Christian Education",
          Organization: "Lakewood Church",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "Planned Giving",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Planned Giving",
          ListTitle: "Planned Giving",
          Organization: "Lakewood Church",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "Grupos con Vida",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Grupos con Vida",
          ListTitle: "Grupos con Vida",
          Organization: "Iglesia Lakewood",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "Ninos con Vida",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Ninos con Vida",
          ListTitle: "Niños con Vida",
          Organization: "Iglesia Lakewood",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "Conexion Jr High",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Conexion Jr High",
          ListTitle: "Conexión Jr High",
          Organization: "Iglesia Lakewood",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "Conexion HS",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Conexion HS",
          ListTitle: "Conexión HS",
          Organization: "Iglesia Lakewood",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "Conexion 19 Plus",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Conexion 19 Plus",
          ListTitle: "Conexión 19+",
          Organization: "Iglesia Lakewood",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "Ministerio de Hombre",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Ministerio de Hombre",
          ListTitle: "Ministerio de Hombre",
          Organization: "Iglesia Lakewood",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "Ministerio de Mujeres",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Ministerio de Mujeres",
          ListTitle: "Ministerio de Mujeres",
          Organization: "Iglesia Lakewood",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "Matrimonios con Vida",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Matrimonios con Vida",
          ListTitle: "Matrimonios con Vida",
          Organization: "Iglesia Lakewood",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "Celebremos la Recuperacion",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Celebremos la Recuperacion",
          ListTitle: "Celebremos la Recuperación",
          Organization: "Iglesia Lakewood",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "Rumbo Norte",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Rumbo Norte",
          ListTitle: "Rumbo Norte",
          Organization: "Iglesia Lakewood",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "Nuevos Convertidos",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Nuevos Convertidos",
          ListTitle: "Nuevos Convertidos",
          Organization: "Iglesia Lakewood",
          IsInterest: true,
          Site: null,
        },
        {
          ListName: "Emprendedores",
          IsSubscribed: false,
          EmailAddress: null,
          OptedIn: null,
          OptedOut: null,
          Status: "Unsub",
          Description: "Emprendedores",
          ListTitle: "Emprendedores",
          Organization: "Iglesia Lakewood",
          IsInterest: true,
          Site: null,
        },
      ],
    })
  );
