import { IStateDetailsAPIResult } from "./CommonTypes";

export const SPOOFED_GET_StateDetails_USA: IStateDetailsAPIResult = JSON.parse(
    JSON.stringify({
        results: [
            {
                Name: "(U.S.) Virgin Islands",
                Iso2Code: "VI",
                Country: {
                    Name: "UNITED STATES",
                    Iso2Code: "US",
                    Iso3Code: "USA",
                    IsSelected: false,
                    CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Id: "752029fe-6ea9-df11-9532-005056954cab",
                },
                IsSelected: false,
            },
            {
                Name: "Alabama",
                Iso2Code: "AL",
                Country: {
                    Name: "UNITED STATES",
                    Iso2Code: "US",
                    Iso3Code: "USA",
                    IsSelected: false,
                    CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Id: "752029fe-6ea9-df11-9532-005056954cab",
                },
                IsSelected: false,
            },
            {
                Name: "Alaska",
                Iso2Code: "AK",
                Country: {
                    Name: "UNITED STATES",
                    Iso2Code: "US",
                    Iso3Code: "USA",
                    IsSelected: false,
                    CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Id: "752029fe-6ea9-df11-9532-005056954cab",
                },
                IsSelected: false,
            },
            {
                Name: "American Samoa",
                Iso2Code: "AS",
                Country: {
                    Name: "UNITED STATES",
                    Iso2Code: "US",
                    Iso3Code: "USA",
                    IsSelected: false,
                    CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Id: "752029fe-6ea9-df11-9532-005056954cab",
                },
                IsSelected: false,
            },
            {
                Name: "American Somoa",
                Iso2Code: "AS",
                Country: {
                    Name: "UNITED STATES",
                    Iso2Code: "US",
                    Iso3Code: "USA",
                    IsSelected: false,
                    CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Id: "752029fe-6ea9-df11-9532-005056954cab",
                },
                IsSelected: false,
            },
            {
                Name: "Arizona",
                Iso2Code: "AZ",
                Country: {
                    Name: "UNITED STATES",
                    Iso2Code: "US",
                    Iso3Code: "USA",
                    IsSelected: false,
                    CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Id: "752029fe-6ea9-df11-9532-005056954cab",
                },
                IsSelected: false,
            },
            {
                Name: "Arkansas",
                Iso2Code: "AR",
                Country: {
                    Name: "UNITED STATES",
                    Iso2Code: "US",
                    Iso3Code: "USA",
                    IsSelected: false,
                    CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Id: "752029fe-6ea9-df11-9532-005056954cab",
                },
                IsSelected: false,
            },
            {
                Name: "Armed Forces, Europe",
                Iso2Code: "AE",
                Country: {
                    Name: "UNITED STATES",
                    Iso2Code: "US",
                    Iso3Code: "USA",
                    IsSelected: false,
                    CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Id: "752029fe-6ea9-df11-9532-005056954cab",
                },
                IsSelected: false,
            },
            {
                Name: "Armed Forces, Pacific",
                Iso2Code: "AP",
                Country: {
                    Name: "UNITED STATES",
                    Iso2Code: "US",
                    Iso3Code: "USA",
                    IsSelected: false,
                    CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Id: "752029fe-6ea9-df11-9532-005056954cab",
                },
                IsSelected: false,
            },
            {
                Name: "Armed Forces, the Americas",
                Iso2Code: "AA",
                Country: {
                    Name: "UNITED STATES",
                    Iso2Code: "US",
                    Iso3Code: "USA",
                    IsSelected: false,
                    CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Id: "752029fe-6ea9-df11-9532-005056954cab",
                },
                IsSelected: false,
            },
            {
                Name: "California",
                Iso2Code: "CA",
                Country: {
                    Name: "UNITED STATES",
                    Iso2Code: "US",
                    Iso3Code: "USA",
                    IsSelected: false,
                    CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Id: "752029fe-6ea9-df11-9532-005056954cab",
                },
                IsSelected: false,
            },
            {
                Name: "Colorado",
                Iso2Code: "CO",
                Country: {
                    Name: "UNITED STATES",
                    Iso2Code: "US",
                    Iso3Code: "USA",
                    IsSelected: false,
                    CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Id: "752029fe-6ea9-df11-9532-005056954cab",
                },
                IsSelected: false,
            },
            {
                Name: "Connecticut",
                Iso2Code: "CT",
                Country: {
                    Name: "UNITED STATES",
                    Iso2Code: "US",
                    Iso3Code: "USA",
                    IsSelected: false,
                    CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Id: "752029fe-6ea9-df11-9532-005056954cab",
                },
                IsSelected: false,
            },
            {
                Name: "Delaware",
                Iso2Code: "DE",
                Country: {
                    Name: "UNITED STATES",
                    Iso2Code: "US",
                    Iso3Code: "USA",
                    IsSelected: false,
                    CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Id: "752029fe-6ea9-df11-9532-005056954cab",
                },
                IsSelected: false,
            },
            {
                Name: "District of Columbia",
                Iso2Code: "DC",
                Country: {
                    Name: "UNITED STATES",
                    Iso2Code: "US",
                    Iso3Code: "USA",
                    IsSelected: false,
                    CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Id: "752029fe-6ea9-df11-9532-005056954cab",
                },
                IsSelected: false,
            },
            {
                Name: "Florida",
                Iso2Code: "FL",
                Country: {
                    Name: "UNITED STATES",
                    Iso2Code: "US",
                    Iso3Code: "USA",
                    IsSelected: false,
                    CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Id: "752029fe-6ea9-df11-9532-005056954cab",
                },
                IsSelected: false,
            },
            {
                Name: "Georgia",
                Iso2Code: "GA",
                Country: {
                    Name: "UNITED STATES",
                    Iso2Code: "US",
                    Iso3Code: "USA",
                    IsSelected: false,
                    CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Id: "752029fe-6ea9-df11-9532-005056954cab",
                },
                IsSelected: false,
            },
            {
                Name: "Guam",
                Iso2Code: "GU",
                Country: {
                    Name: "UNITED STATES",
                    Iso2Code: "US",
                    Iso3Code: "USA",
                    IsSelected: false,
                    CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Id: "752029fe-6ea9-df11-9532-005056954cab",
                },
                IsSelected: false,
            },
            {
                Name: "Hawaii",
                Iso2Code: "HI",
                Country: {
                    Name: "UNITED STATES",
                    Iso2Code: "US",
                    Iso3Code: "USA",
                    IsSelected: false,
                    CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Id: "752029fe-6ea9-df11-9532-005056954cab",
                },
                IsSelected: false,
            },
            {
                Name: "Idaho",
                Iso2Code: "ID",
                Country: {
                    Name: "UNITED STATES",
                    Iso2Code: "US",
                    Iso3Code: "USA",
                    IsSelected: false,
                    CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Id: "752029fe-6ea9-df11-9532-005056954cab",
                },
                IsSelected: false,
            },
            {
                Name: "Illinois",
                Iso2Code: "IL",
                Country: {
                    Name: "UNITED STATES",
                    Iso2Code: "US",
                    Iso3Code: "USA",
                    IsSelected: false,
                    CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Id: "752029fe-6ea9-df11-9532-005056954cab",
                },
                IsSelected: false,
            },
            {
                Name: "Indiana",
                Iso2Code: "IN",
                Country: {
                    Name: "UNITED STATES",
                    Iso2Code: "US",
                    Iso3Code: "USA",
                    IsSelected: false,
                    CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Id: "752029fe-6ea9-df11-9532-005056954cab",
                },
                IsSelected: false,
            },
            {
                Name: "Iowa",
                Iso2Code: "IA",
                Country: {
                    Name: "UNITED STATES",
                    Iso2Code: "US",
                    Iso3Code: "USA",
                    IsSelected: false,
                    CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Id: "752029fe-6ea9-df11-9532-005056954cab",
                },
                IsSelected: false,
            },
            {
                Name: "Kansas",
                Iso2Code: "KS",
                Country: {
                    Name: "UNITED STATES",
                    Iso2Code: "US",
                    Iso3Code: "USA",
                    IsSelected: false,
                    CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Id: "752029fe-6ea9-df11-9532-005056954cab",
                },
                IsSelected: false,
            },
            {
                Name: "Kentucky",
                Iso2Code: "KY",
                Country: {
                    Name: "UNITED STATES",
                    Iso2Code: "US",
                    Iso3Code: "USA",
                    IsSelected: false,
                    CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Id: "752029fe-6ea9-df11-9532-005056954cab",
                },
                IsSelected: false,
            },
            {
                Name: "Louisiana",
                Iso2Code: "LA",
                Country: {
                    Name: "UNITED STATES",
                    Iso2Code: "US",
                    Iso3Code: "USA",
                    IsSelected: false,
                    CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Id: "752029fe-6ea9-df11-9532-005056954cab",
                },
                IsSelected: false,
            },
            {
                Name: "Maine",
                Iso2Code: "ME",
                Country: {
                    Name: "UNITED STATES",
                    Iso2Code: "US",
                    Iso3Code: "USA",
                    IsSelected: false,
                    CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Id: "752029fe-6ea9-df11-9532-005056954cab",
                },
                IsSelected: false,
            },
            {
                Name: "Marshall Islands",
                Iso2Code: "MH",
                Country: {
                    Name: "UNITED STATES",
                    Iso2Code: "US",
                    Iso3Code: "USA",
                    IsSelected: false,
                    CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Id: "752029fe-6ea9-df11-9532-005056954cab",
                },
                IsSelected: false,
            },
            {
                Name: "Maryland",
                Iso2Code: "MD",
                Country: {
                    Name: "UNITED STATES",
                    Iso2Code: "US",
                    Iso3Code: "USA",
                    IsSelected: false,
                    CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Id: "752029fe-6ea9-df11-9532-005056954cab",
                },
                IsSelected: false,
            },
            {
                Name: "Massachusetts",
                Iso2Code: "MA",
                Country: {
                    Name: "UNITED STATES",
                    Iso2Code: "US",
                    Iso3Code: "USA",
                    IsSelected: false,
                    CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Id: "752029fe-6ea9-df11-9532-005056954cab",
                },
                IsSelected: false,
            },
            {
                Name: "Michigan",
                Iso2Code: "MI",
                Country: {
                    Name: "UNITED STATES",
                    Iso2Code: "US",
                    Iso3Code: "USA",
                    IsSelected: false,
                    CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Id: "752029fe-6ea9-df11-9532-005056954cab",
                },
                IsSelected: false,
            },
            {
                Name: "Minnesota",
                Iso2Code: "MN",
                Country: {
                    Name: "UNITED STATES",
                    Iso2Code: "US",
                    Iso3Code: "USA",
                    IsSelected: false,
                    CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Id: "752029fe-6ea9-df11-9532-005056954cab",
                },
                IsSelected: false,
            },
            {
                Name: "Mississippi",
                Iso2Code: "MS",
                Country: {
                    Name: "UNITED STATES",
                    Iso2Code: "US",
                    Iso3Code: "USA",
                    IsSelected: false,
                    CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Id: "752029fe-6ea9-df11-9532-005056954cab",
                },
                IsSelected: false,
            },
            {
                Name: "Missouri",
                Iso2Code: "MO",
                Country: {
                    Name: "UNITED STATES",
                    Iso2Code: "US",
                    Iso3Code: "USA",
                    IsSelected: false,
                    CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Id: "752029fe-6ea9-df11-9532-005056954cab",
                },
                IsSelected: false,
            },
            {
                Name: "Montana",
                Iso2Code: "MT",
                Country: {
                    Name: "UNITED STATES",
                    Iso2Code: "US",
                    Iso3Code: "USA",
                    IsSelected: false,
                    CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Id: "752029fe-6ea9-df11-9532-005056954cab",
                },
                IsSelected: false,
            },
            {
                Name: "Nebraska",
                Iso2Code: "NE",
                Country: {
                    Name: "UNITED STATES",
                    Iso2Code: "US",
                    Iso3Code: "USA",
                    IsSelected: false,
                    CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Id: "752029fe-6ea9-df11-9532-005056954cab",
                },
                IsSelected: false,
            },
            {
                Name: "Nevada",
                Iso2Code: "NV",
                Country: {
                    Name: "UNITED STATES",
                    Iso2Code: "US",
                    Iso3Code: "USA",
                    IsSelected: false,
                    CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Id: "752029fe-6ea9-df11-9532-005056954cab",
                },
                IsSelected: false,
            },
            {
                Name: "New Hampshire",
                Iso2Code: "NH",
                Country: {
                    Name: "UNITED STATES",
                    Iso2Code: "US",
                    Iso3Code: "USA",
                    IsSelected: false,
                    CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Id: "752029fe-6ea9-df11-9532-005056954cab",
                },
                IsSelected: false,
            },
            {
                Name: "New Jersey",
                Iso2Code: "NJ",
                Country: {
                    Name: "UNITED STATES",
                    Iso2Code: "US",
                    Iso3Code: "USA",
                    IsSelected: false,
                    CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Id: "752029fe-6ea9-df11-9532-005056954cab",
                },
                IsSelected: false,
            },
            {
                Name: "New Mexico",
                Iso2Code: "NM",
                Country: {
                    Name: "UNITED STATES",
                    Iso2Code: "US",
                    Iso3Code: "USA",
                    IsSelected: false,
                    CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Id: "752029fe-6ea9-df11-9532-005056954cab",
                },
                IsSelected: false,
            },
            {
                Name: "New York",
                Iso2Code: "NY",
                Country: {
                    Name: "UNITED STATES",
                    Iso2Code: "US",
                    Iso3Code: "USA",
                    IsSelected: false,
                    CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Id: "752029fe-6ea9-df11-9532-005056954cab",
                },
                IsSelected: false,
            },
            {
                Name: "North Carolina",
                Iso2Code: "NC",
                Country: {
                    Name: "UNITED STATES",
                    Iso2Code: "US",
                    Iso3Code: "USA",
                    IsSelected: false,
                    CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Id: "752029fe-6ea9-df11-9532-005056954cab",
                },
                IsSelected: false,
            },
            {
                Name: "North Dakota",
                Iso2Code: "ND",
                Country: {
                    Name: "UNITED STATES",
                    Iso2Code: "US",
                    Iso3Code: "USA",
                    IsSelected: false,
                    CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Id: "752029fe-6ea9-df11-9532-005056954cab",
                },
                IsSelected: false,
            },
            {
                Name: "Northern Marianas",
                Iso2Code: "MP",
                Country: {
                    Name: "UNITED STATES",
                    Iso2Code: "US",
                    Iso3Code: "USA",
                    IsSelected: false,
                    CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Id: "752029fe-6ea9-df11-9532-005056954cab",
                },
                IsSelected: false,
            },
            {
                Name: "Ohio",
                Iso2Code: "OH",
                Country: {
                    Name: "UNITED STATES",
                    Iso2Code: "US",
                    Iso3Code: "USA",
                    IsSelected: false,
                    CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Id: "752029fe-6ea9-df11-9532-005056954cab",
                },
                IsSelected: false,
            },
            {
                Name: "Oklahoma",
                Iso2Code: "OK",
                Country: {
                    Name: "UNITED STATES",
                    Iso2Code: "US",
                    Iso3Code: "USA",
                    IsSelected: false,
                    CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Id: "752029fe-6ea9-df11-9532-005056954cab",
                },
                IsSelected: false,
            },
            {
                Name: "Oregon",
                Iso2Code: "OR",
                Country: {
                    Name: "UNITED STATES",
                    Iso2Code: "US",
                    Iso3Code: "USA",
                    IsSelected: false,
                    CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Id: "752029fe-6ea9-df11-9532-005056954cab",
                },
                IsSelected: false,
            },
            {
                Name: "Pennsylvania",
                Iso2Code: "PA",
                Country: {
                    Name: "UNITED STATES",
                    Iso2Code: "US",
                    Iso3Code: "USA",
                    IsSelected: false,
                    CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Id: "752029fe-6ea9-df11-9532-005056954cab",
                },
                IsSelected: false,
            },
            {
                Name: "Puerto Rico",
                Iso2Code: "PR",
                Country: {
                    Name: "UNITED STATES",
                    Iso2Code: "US",
                    Iso3Code: "USA",
                    IsSelected: false,
                    CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Id: "752029fe-6ea9-df11-9532-005056954cab",
                },
                IsSelected: false,
            },
            {
                Name: "Rhode Island",
                Iso2Code: "RI",
                Country: {
                    Name: "UNITED STATES",
                    Iso2Code: "US",
                    Iso3Code: "USA",
                    IsSelected: false,
                    CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Id: "752029fe-6ea9-df11-9532-005056954cab",
                },
                IsSelected: false,
            },
            {
                Name: "South Carolina",
                Iso2Code: "SC",
                Country: {
                    Name: "UNITED STATES",
                    Iso2Code: "US",
                    Iso3Code: "USA",
                    IsSelected: false,
                    CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Id: "752029fe-6ea9-df11-9532-005056954cab",
                },
                IsSelected: false,
            },
            {
                Name: "South Dakota",
                Iso2Code: "SD",
                Country: {
                    Name: "UNITED STATES",
                    Iso2Code: "US",
                    Iso3Code: "USA",
                    IsSelected: false,
                    CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Id: "752029fe-6ea9-df11-9532-005056954cab",
                },
                IsSelected: false,
            },
            {
                Name: "Tennessee",
                Iso2Code: "TN",
                Country: {
                    Name: "UNITED STATES",
                    Iso2Code: "US",
                    Iso3Code: "USA",
                    IsSelected: false,
                    CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Id: "752029fe-6ea9-df11-9532-005056954cab",
                },
                IsSelected: false,
            },
            {
                Name: "Texas",
                Iso2Code: "TX",
                Country: {
                    Name: "UNITED STATES",
                    Iso2Code: "US",
                    Iso3Code: "USA",
                    IsSelected: false,
                    CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Id: "752029fe-6ea9-df11-9532-005056954cab",
                },
                IsSelected: false,
            },
            {
                Name: "Utah",
                Iso2Code: "UT",
                Country: {
                    Name: "UNITED STATES",
                    Iso2Code: "US",
                    Iso3Code: "USA",
                    IsSelected: false,
                    CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Id: "752029fe-6ea9-df11-9532-005056954cab",
                },
                IsSelected: false,
            },
            {
                Name: "Vermont",
                Iso2Code: "VT",
                Country: {
                    Name: "UNITED STATES",
                    Iso2Code: "US",
                    Iso3Code: "USA",
                    IsSelected: false,
                    CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Id: "752029fe-6ea9-df11-9532-005056954cab",
                },
                IsSelected: false,
            },
            {
                Name: "Virginia",
                Iso2Code: "VA",
                Country: {
                    Name: "UNITED STATES",
                    Iso2Code: "US",
                    Iso3Code: "USA",
                    IsSelected: false,
                    CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Id: "752029fe-6ea9-df11-9532-005056954cab",
                },
                IsSelected: false,
            },
            {
                Name: "Washington",
                Iso2Code: "WA",
                Country: {
                    Name: "UNITED STATES",
                    Iso2Code: "US",
                    Iso3Code: "USA",
                    IsSelected: false,
                    CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Id: "752029fe-6ea9-df11-9532-005056954cab",
                },
                IsSelected: false,
            },
            {
                Name: "West Virginia",
                Iso2Code: "WV",
                Country: {
                    Name: "UNITED STATES",
                    Iso2Code: "US",
                    Iso3Code: "USA",
                    IsSelected: false,
                    CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Id: "752029fe-6ea9-df11-9532-005056954cab",
                },
                IsSelected: false,
            },
            {
                Name: "Wisconsin",
                Iso2Code: "WI",
                Country: {
                    Name: "UNITED STATES",
                    Iso2Code: "US",
                    Iso3Code: "USA",
                    IsSelected: false,
                    CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Id: "752029fe-6ea9-df11-9532-005056954cab",
                },
                IsSelected: false,
            },
            {
                Name: "Wyoming",
                Iso2Code: "WY",
                Country: {
                    Name: "UNITED STATES",
                    Iso2Code: "US",
                    Iso3Code: "USA",
                    IsSelected: false,
                    CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Id: "752029fe-6ea9-df11-9532-005056954cab",
                },
                IsSelected: false,
            },
        ],
    })
);

export const SPOOFED_GET_StateDetails_CANADA: IStateDetailsAPIResult =
    JSON.parse(
        JSON.stringify({
            results: [
                {
                    Name: "Alberta",
                    Iso2Code: "AB",
                    Country: {
                        Name: "CANADA",
                        Iso2Code: "CA",
                        Iso3Code: "CAN",
                        IsSelected: false,
                        CurrencyId: "240be69d-a7af-df11-9793-005056952aae",
                        Id: "b21f29fe-6ea9-df11-9532-005056954cab",
                    },
                    IsSelected: false,
                },
                {
                    Name: "British Columbia",
                    Iso2Code: "BC",
                    Country: {
                        Name: "CANADA",
                        Iso2Code: "CA",
                        Iso3Code: "CAN",
                        IsSelected: false,
                        CurrencyId: "240be69d-a7af-df11-9793-005056952aae",
                        Id: "b21f29fe-6ea9-df11-9532-005056954cab",
                    },
                    IsSelected: false,
                },
                {
                    Name: "Manitoba",
                    Iso2Code: "MB",
                    Country: {
                        Name: "CANADA",
                        Iso2Code: "CA",
                        Iso3Code: "CAN",
                        IsSelected: false,
                        CurrencyId: "240be69d-a7af-df11-9793-005056952aae",
                        Id: "b21f29fe-6ea9-df11-9532-005056954cab",
                    },
                    IsSelected: false,
                },
                {
                    Name: "New Brunswick",
                    Iso2Code: "NB",
                    Country: {
                        Name: "CANADA",
                        Iso2Code: "CA",
                        Iso3Code: "CAN",
                        IsSelected: false,
                        CurrencyId: "240be69d-a7af-df11-9793-005056952aae",
                        Id: "b21f29fe-6ea9-df11-9532-005056954cab",
                    },
                    IsSelected: false,
                },
                {
                    Name: "Newfoundland and Labrador",
                    Iso2Code: "NL",
                    Country: {
                        Name: "CANADA",
                        Iso2Code: "CA",
                        Iso3Code: "CAN",
                        IsSelected: false,
                        CurrencyId: "240be69d-a7af-df11-9793-005056952aae",
                        Id: "b21f29fe-6ea9-df11-9532-005056954cab",
                    },
                    IsSelected: false,
                },
                {
                    Name: "Northwest Territories",
                    Iso2Code: "NT",
                    Country: {
                        Name: "CANADA",
                        Iso2Code: "CA",
                        Iso3Code: "CAN",
                        IsSelected: false,
                        CurrencyId: "240be69d-a7af-df11-9793-005056952aae",
                        Id: "b21f29fe-6ea9-df11-9532-005056954cab",
                    },
                    IsSelected: false,
                },
                {
                    Name: "Nova Scotia",
                    Iso2Code: "NS",
                    Country: {
                        Name: "CANADA",
                        Iso2Code: "CA",
                        Iso3Code: "CAN",
                        IsSelected: false,
                        CurrencyId: "240be69d-a7af-df11-9793-005056952aae",
                        Id: "b21f29fe-6ea9-df11-9532-005056954cab",
                    },
                    IsSelected: false,
                },
                {
                    Name: "Nunavut",
                    Iso2Code: "NU",
                    Country: {
                        Name: "CANADA",
                        Iso2Code: "CA",
                        Iso3Code: "CAN",
                        IsSelected: false,
                        CurrencyId: "240be69d-a7af-df11-9793-005056952aae",
                        Id: "b21f29fe-6ea9-df11-9532-005056954cab",
                    },
                    IsSelected: false,
                },
                {
                    Name: "Ontario",
                    Iso2Code: "ON",
                    Country: {
                        Name: "CANADA",
                        Iso2Code: "CA",
                        Iso3Code: "CAN",
                        IsSelected: false,
                        CurrencyId: "240be69d-a7af-df11-9793-005056952aae",
                        Id: "b21f29fe-6ea9-df11-9532-005056954cab",
                    },
                    IsSelected: false,
                },
                {
                    Name: "Prince Edward Island",
                    Iso2Code: "PE",
                    Country: {
                        Name: "CANADA",
                        Iso2Code: "CA",
                        Iso3Code: "CAN",
                        IsSelected: false,
                        CurrencyId: "240be69d-a7af-df11-9793-005056952aae",
                        Id: "b21f29fe-6ea9-df11-9532-005056954cab",
                    },
                    IsSelected: false,
                },
                {
                    Name: "Québec",
                    Iso2Code: "QC",
                    Country: {
                        Name: "CANADA",
                        Iso2Code: "CA",
                        Iso3Code: "CAN",
                        IsSelected: false,
                        CurrencyId: "240be69d-a7af-df11-9793-005056952aae",
                        Id: "b21f29fe-6ea9-df11-9532-005056954cab",
                    },
                    IsSelected: false,
                },
                {
                    Name: "Saskatchewan",
                    Iso2Code: "SK",
                    Country: {
                        Name: "CANADA",
                        Iso2Code: "CA",
                        Iso3Code: "CAN",
                        IsSelected: false,
                        CurrencyId: "240be69d-a7af-df11-9793-005056952aae",
                        Id: "b21f29fe-6ea9-df11-9532-005056954cab",
                    },
                    IsSelected: false,
                },
                {
                    Name: "Yukon Territory",
                    Iso2Code: "YT",
                    Country: {
                        Name: "CANADA",
                        Iso2Code: "CA",
                        Iso3Code: "CAN",
                        IsSelected: false,
                        CurrencyId: "240be69d-a7af-df11-9793-005056952aae",
                        Id: "b21f29fe-6ea9-df11-9532-005056954cab",
                    },
                    IsSelected: false,
                },
            ],
        })
    );

