import {
    IOrderHeadersAPIResult,
    IOrderDetailsAPIResult,
} from "./TransactionDetailsTypes";

export const SPOOFED_GET_OrderHeaders: IOrderHeadersAPIResult = JSON.parse(
    JSON.stringify({
        results: [
            {
                Id: "a82365fe-6274-ee11-9ae7-000d3a18283a",
                Contact: {
                    Id: "3302a646-1536-ee11-bdf4-000d3a190fe1",
                    IsLoggedIn: true,
                    IsGuest: false,
                    IsPartner: false,
                    Security: {
                        IsAdmin: false,
                        SecurityRoles: null,
                        SecurityFlags: null,
                        SecurityAuthority: null,
                    },
                    Address: {
                        Id: "b8063c8c-6264-4fec-aee0-238d9a8718f5",
                        CustomerId: null,
                        FirstName: "Don",
                        LastName: "Test",
                        IsPrimary: true,
                        IsDefaultBilling: false,
                        IsDefaultShipping: false,
                        IsSelected: false,
                        City: "INDIAN TRAIL",
                        StateDetail: {
                            Name: "North Carolina",
                            Iso2Code: "NC",
                            Country: null,
                            IsSelected: false,
                        },
                        DoNotMail: false,
                        State: "NC",
                        CountryDetail: {
                            Name: "UNITED STATES",
                            Iso2Code: "US",
                            Iso3Code: "USA",
                            IsSelected: false,
                            CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                            Id: "752029fe-6ea9-df11-9532-005056954cab",
                        },
                        Country: "UNITED STATES",
                        Summary:
                            "5507 Fulton Ridge Drive, Suite 4, INDIAN TRAIL, NC, 28079, UNITED STATES",
                        Latitude: 0.0,
                        Longitude: 0.0,
                        Line1: "5507 Fulton Ridge Drive",
                        Line2: "Suite 4",
                        Person: null,
                        Name: null,
                        PostalCode: "28079",
                        HasBasicData: true,
                    },
                    DefaultBillingAddress: {
                        Id: "8dde102e-8bf8-45d3-a0b1-00b5cb56a647",
                        CustomerId: null,
                        FirstName: "Don",
                        LastName: "Test",
                        IsPrimary: true,
                        IsDefaultBilling: false,
                        IsDefaultShipping: false,
                        IsSelected: false,
                        City: "INDIAN TRAIL",
                        StateDetail: {
                            Name: "North Carolina",
                            Iso2Code: "NC",
                            Country: null,
                            IsSelected: false,
                        },
                        DoNotMail: false,
                        State: "NC",
                        CountryDetail: {
                            Name: "UNITED STATES",
                            Iso2Code: "US",
                            Iso3Code: "USA",
                            IsSelected: false,
                            CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                            Id: "752029fe-6ea9-df11-9532-005056954cab",
                        },
                        Country: "UNITED STATES",
                        Summary:
                            "5507 Fulton Ridge Drive, Suite 4, INDIAN TRAIL, NC, 28079, UNITED STATES",
                        Latitude: 0.0,
                        Longitude: 0.0,
                        Line1: "5507 Fulton Ridge Drive",
                        Line2: "Suite 4",
                        Person: null,
                        Name: null,
                        PostalCode: "28079",
                        HasBasicData: true,
                    },
                    DefaultShippingAddress: {
                        Id: "67dd5c11-62a1-42e0-bc07-d62a63cdf671",
                        CustomerId: null,
                        FirstName: "Don",
                        LastName: "Test",
                        IsPrimary: true,
                        IsDefaultBilling: false,
                        IsDefaultShipping: false,
                        IsSelected: false,
                        City: "INDIAN TRAIL",
                        StateDetail: {
                            Name: "North Carolina",
                            Iso2Code: "NC",
                            Country: null,
                            IsSelected: false,
                        },
                        DoNotMail: false,
                        State: "NC",
                        CountryDetail: {
                            Name: "UNITED STATES",
                            Iso2Code: "US",
                            Iso3Code: "USA",
                            IsSelected: false,
                            CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                            Id: "752029fe-6ea9-df11-9532-005056954cab",
                        },
                        Country: "UNITED STATES",
                        Summary:
                            "5507 Fulton Ridge Drive, Suite 4, INDIAN TRAIL, NC, 28079, UNITED STATES",
                        Latitude: 0.0,
                        Longitude: 0.0,
                        Line1: "5507 Fulton Ridge Drive",
                        Line2: "Suite 4",
                        Person: null,
                        Name: null,
                        PostalCode: "28079",
                        HasBasicData: true,
                    },
                    BirthDate: null,
                    DoNotEmail: true,
                    DoNotPhone: true,
                    DoNotCallMobile: null,
                    AllowSMS: null,
                    DoNotPostalMail: false,
                    PrimaryEmailAddress: "ven-dobrien@lakewood.cc",
                    FirstName: "Don",
                    LastName: "Test",
                    FullName: "Don Test",
                    Gender: 3,
                    Acno: "C011006381",
                    Church: null,
                    Discount: 0.0,
                    PriceLevelId: "5f7fcdb8-a87a-e611-80c9-000d3a700f55",
                    Facebook: null,
                    Instagram: null,
                    TaxExempt: false,
                    Twitter: null,
                    LastLogin: "2023-10-30T18:29:25Z",
                    IsPrivate: false,
                    PhoneNumber: null,
                    MobilePhoneNumber: null,
                    SiteCode: "JOM",
                    Sourcecode: "2300JW",
                    CreatedOn: "2023-08-08T17:59:18Z",
                    LastDonationAmount: 0.0,
                    HighestDonationAmount: 0.0,
                    AverageDonationAmount: 0.0,
                    GiftAskLow: 10.0,
                    GiftAskMid: 15.0,
                    GiftAskHigh: 25.0,
                    JOMMobile: null,
                    LWCMobile: null,
                    DonorFrequency: "",
                    DonorType: "",
                    GivingHistory: [
                        {
                            Key: "2023",
                            Value: 0.0,
                        },
                    ],
                    AuthToken: null,
                    RedirectUrl: null,
                    DefaultCurrency: {
                        Id: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                        Name: "US Dollar",
                        Symbol: "$",
                        Iso3Code: "USD",
                        IsSelected: false,
                    },
                    AdminChurches: null,
                },
                CustomerId: "3302a646-1536-ee11-bdf4-000d3a190fe1",
                Payments: null,
                OrderItems: null,
                Status: 0,
                Discount: 0.0,
                Shipping: 0.0,
                ProductTotal: 25.0,
                DonationTotal: 0.0,
                EventTotal: 0.0,
                Subtotal: 0.0,
                Tax: 0.0,
                Total: 25.0,
                IsWebOrder: false,
                OrderDate: "2023-10-26T19:51:52",
                IsFromRecurringGift: false,
                OrderNumber: "ORD-4511940-S8R4F9",
                CurrencySymbol: "$",
                Currency: {
                    Id: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Name: "US Dollar",
                    Symbol: "$",
                    Iso3Code: "USD",
                    IsSelected: false,
                },
                StatusString: "0",
                TrackingNumbers: "",
            },
            {
                Id: "86713d5a-6274-ee11-9ae7-000d3a18283a",
                Contact: {
                    Id: "3302a646-1536-ee11-bdf4-000d3a190fe1",
                    IsLoggedIn: true,
                    IsGuest: false,
                    IsPartner: false,
                    Security: {
                        IsAdmin: false,
                        SecurityRoles: null,
                        SecurityFlags: null,
                        SecurityAuthority: null,
                    },
                    Address: {
                        Id: "b8063c8c-6264-4fec-aee0-238d9a8718f5",
                        CustomerId: null,
                        FirstName: "Don",
                        LastName: "Test",
                        IsPrimary: true,
                        IsDefaultBilling: false,
                        IsDefaultShipping: false,
                        IsSelected: false,
                        City: "INDIAN TRAIL",
                        StateDetail: {
                            Name: "North Carolina",
                            Iso2Code: "NC",
                            Country: null,
                            IsSelected: false,
                        },
                        DoNotMail: false,
                        State: "NC",
                        CountryDetail: {
                            Name: "UNITED STATES",
                            Iso2Code: "US",
                            Iso3Code: "USA",
                            IsSelected: false,
                            CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                            Id: "752029fe-6ea9-df11-9532-005056954cab",
                        },
                        Country: "UNITED STATES",
                        Summary:
                            "5507 Fulton Ridge Drive, Suite 4, INDIAN TRAIL, NC, 28079, UNITED STATES",
                        Latitude: 0.0,
                        Longitude: 0.0,
                        Line1: "5507 Fulton Ridge Drive",
                        Line2: "Suite 4",
                        Person: null,
                        Name: null,
                        PostalCode: "28079",
                        HasBasicData: true,
                    },
                    DefaultBillingAddress: {
                        Id: "8dde102e-8bf8-45d3-a0b1-00b5cb56a647",
                        CustomerId: null,
                        FirstName: "Don",
                        LastName: "Test",
                        IsPrimary: true,
                        IsDefaultBilling: false,
                        IsDefaultShipping: false,
                        IsSelected: false,
                        City: "INDIAN TRAIL",
                        StateDetail: {
                            Name: "North Carolina",
                            Iso2Code: "NC",
                            Country: null,
                            IsSelected: false,
                        },
                        DoNotMail: false,
                        State: "NC",
                        CountryDetail: {
                            Name: "UNITED STATES",
                            Iso2Code: "US",
                            Iso3Code: "USA",
                            IsSelected: false,
                            CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                            Id: "752029fe-6ea9-df11-9532-005056954cab",
                        },
                        Country: "UNITED STATES",
                        Summary:
                            "5507 Fulton Ridge Drive, Suite 4, INDIAN TRAIL, NC, 28079, UNITED STATES",
                        Latitude: 0.0,
                        Longitude: 0.0,
                        Line1: "5507 Fulton Ridge Drive",
                        Line2: "Suite 4",
                        Person: null,
                        Name: null,
                        PostalCode: "28079",
                        HasBasicData: true,
                    },
                    DefaultShippingAddress: {
                        Id: "67dd5c11-62a1-42e0-bc07-d62a63cdf671",
                        CustomerId: null,
                        FirstName: "Don",
                        LastName: "Test",
                        IsPrimary: true,
                        IsDefaultBilling: false,
                        IsDefaultShipping: false,
                        IsSelected: false,
                        City: "INDIAN TRAIL",
                        StateDetail: {
                            Name: "North Carolina",
                            Iso2Code: "NC",
                            Country: null,
                            IsSelected: false,
                        },
                        DoNotMail: false,
                        State: "NC",
                        CountryDetail: {
                            Name: "UNITED STATES",
                            Iso2Code: "US",
                            Iso3Code: "USA",
                            IsSelected: false,
                            CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                            Id: "752029fe-6ea9-df11-9532-005056954cab",
                        },
                        Country: "UNITED STATES",
                        Summary:
                            "5507 Fulton Ridge Drive, Suite 4, INDIAN TRAIL, NC, 28079, UNITED STATES",
                        Latitude: 0.0,
                        Longitude: 0.0,
                        Line1: "5507 Fulton Ridge Drive",
                        Line2: "Suite 4",
                        Person: null,
                        Name: null,
                        PostalCode: "28079",
                        HasBasicData: true,
                    },
                    BirthDate: null,
                    DoNotEmail: true,
                    DoNotPhone: true,
                    DoNotCallMobile: null,
                    AllowSMS: null,
                    DoNotPostalMail: false,
                    PrimaryEmailAddress: "ven-dobrien@lakewood.cc",
                    FirstName: "Don",
                    LastName: "Test",
                    FullName: "Don Test",
                    Gender: 3,
                    Acno: "C011006381",
                    Church: null,
                    Discount: 0.0,
                    PriceLevelId: "5f7fcdb8-a87a-e611-80c9-000d3a700f55",
                    Facebook: null,
                    Instagram: null,
                    TaxExempt: false,
                    Twitter: null,
                    LastLogin: "2023-10-30T18:29:25Z",
                    IsPrivate: false,
                    PhoneNumber: null,
                    MobilePhoneNumber: null,
                    SiteCode: "JOM",
                    Sourcecode: "2300JW",
                    CreatedOn: "2023-08-08T17:59:18Z",
                    LastDonationAmount: 0.0,
                    HighestDonationAmount: 0.0,
                    AverageDonationAmount: 0.0,
                    GiftAskLow: 10.0,
                    GiftAskMid: 15.0,
                    GiftAskHigh: 25.0,
                    JOMMobile: null,
                    LWCMobile: null,
                    DonorFrequency: "",
                    DonorType: "",
                    GivingHistory: [
                        {
                            Key: "2023",
                            Value: 0.0,
                        },
                    ],
                    AuthToken: null,
                    RedirectUrl: null,
                    DefaultCurrency: {
                        Id: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                        Name: "US Dollar",
                        Symbol: "$",
                        Iso3Code: "USD",
                        IsSelected: false,
                    },
                    AdminChurches: null,
                },
                CustomerId: "3302a646-1536-ee11-bdf4-000d3a190fe1",
                Payments: null,
                OrderItems: null,
                Status: 0,
                Discount: 0.0,
                Shipping: 0.0,
                ProductTotal: 5.0,
                DonationTotal: 0.0,
                EventTotal: 0.0,
                Subtotal: 0.0,
                Tax: 0.0,
                Total: 5.0,
                IsWebOrder: false,
                OrderDate: "2023-10-26T19:47:10",
                IsFromRecurringGift: false,
                OrderNumber: "ORD-4511939-G2V4K3",
                CurrencySymbol: "$",
                Currency: {
                    Id: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Name: "US Dollar",
                    Symbol: "$",
                    Iso3Code: "USD",
                    IsSelected: false,
                },
                StatusString: "0",
                TrackingNumbers: "",
            },
            {
                Id: "e69403ec-6174-ee11-9ae7-000d3a190fe1",
                Contact: {
                    Id: "3302a646-1536-ee11-bdf4-000d3a190fe1",
                    IsLoggedIn: true,
                    IsGuest: false,
                    IsPartner: false,
                    Security: {
                        IsAdmin: false,
                        SecurityRoles: null,
                        SecurityFlags: null,
                        SecurityAuthority: null,
                    },
                    Address: {
                        Id: "b8063c8c-6264-4fec-aee0-238d9a8718f5",
                        CustomerId: null,
                        FirstName: "Don",
                        LastName: "Test",
                        IsPrimary: true,
                        IsDefaultBilling: false,
                        IsDefaultShipping: false,
                        IsSelected: false,
                        City: "INDIAN TRAIL",
                        StateDetail: {
                            Name: "North Carolina",
                            Iso2Code: "NC",
                            Country: null,
                            IsSelected: false,
                        },
                        DoNotMail: false,
                        State: "NC",
                        CountryDetail: {
                            Name: "UNITED STATES",
                            Iso2Code: "US",
                            Iso3Code: "USA",
                            IsSelected: false,
                            CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                            Id: "752029fe-6ea9-df11-9532-005056954cab",
                        },
                        Country: "UNITED STATES",
                        Summary:
                            "5507 Fulton Ridge Drive, Suite 4, INDIAN TRAIL, NC, 28079, UNITED STATES",
                        Latitude: 0.0,
                        Longitude: 0.0,
                        Line1: "5507 Fulton Ridge Drive",
                        Line2: "Suite 4",
                        Person: null,
                        Name: null,
                        PostalCode: "28079",
                        HasBasicData: true,
                    },
                    DefaultBillingAddress: {
                        Id: "8dde102e-8bf8-45d3-a0b1-00b5cb56a647",
                        CustomerId: null,
                        FirstName: "Don",
                        LastName: "Test",
                        IsPrimary: true,
                        IsDefaultBilling: false,
                        IsDefaultShipping: false,
                        IsSelected: false,
                        City: "INDIAN TRAIL",
                        StateDetail: {
                            Name: "North Carolina",
                            Iso2Code: "NC",
                            Country: null,
                            IsSelected: false,
                        },
                        DoNotMail: false,
                        State: "NC",
                        CountryDetail: {
                            Name: "UNITED STATES",
                            Iso2Code: "US",
                            Iso3Code: "USA",
                            IsSelected: false,
                            CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                            Id: "752029fe-6ea9-df11-9532-005056954cab",
                        },
                        Country: "UNITED STATES",
                        Summary:
                            "5507 Fulton Ridge Drive, Suite 4, INDIAN TRAIL, NC, 28079, UNITED STATES",
                        Latitude: 0.0,
                        Longitude: 0.0,
                        Line1: "5507 Fulton Ridge Drive",
                        Line2: "Suite 4",
                        Person: null,
                        Name: null,
                        PostalCode: "28079",
                        HasBasicData: true,
                    },
                    DefaultShippingAddress: {
                        Id: "67dd5c11-62a1-42e0-bc07-d62a63cdf671",
                        CustomerId: null,
                        FirstName: "Don",
                        LastName: "Test",
                        IsPrimary: true,
                        IsDefaultBilling: false,
                        IsDefaultShipping: false,
                        IsSelected: false,
                        City: "INDIAN TRAIL",
                        StateDetail: {
                            Name: "North Carolina",
                            Iso2Code: "NC",
                            Country: null,
                            IsSelected: false,
                        },
                        DoNotMail: false,
                        State: "NC",
                        CountryDetail: {
                            Name: "UNITED STATES",
                            Iso2Code: "US",
                            Iso3Code: "USA",
                            IsSelected: false,
                            CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                            Id: "752029fe-6ea9-df11-9532-005056954cab",
                        },
                        Country: "UNITED STATES",
                        Summary:
                            "5507 Fulton Ridge Drive, Suite 4, INDIAN TRAIL, NC, 28079, UNITED STATES",
                        Latitude: 0.0,
                        Longitude: 0.0,
                        Line1: "5507 Fulton Ridge Drive",
                        Line2: "Suite 4",
                        Person: null,
                        Name: null,
                        PostalCode: "28079",
                        HasBasicData: true,
                    },
                    BirthDate: null,
                    DoNotEmail: true,
                    DoNotPhone: true,
                    DoNotCallMobile: null,
                    AllowSMS: null,
                    DoNotPostalMail: false,
                    PrimaryEmailAddress: "ven-dobrien@lakewood.cc",
                    FirstName: "Don",
                    LastName: "Test",
                    FullName: "Don Test",
                    Gender: 3,
                    Acno: "C011006381",
                    Church: null,
                    Discount: 0.0,
                    PriceLevelId: "5f7fcdb8-a87a-e611-80c9-000d3a700f55",
                    Facebook: null,
                    Instagram: null,
                    TaxExempt: false,
                    Twitter: null,
                    LastLogin: "2023-10-30T18:29:25Z",
                    IsPrivate: false,
                    PhoneNumber: null,
                    MobilePhoneNumber: null,
                    SiteCode: "JOM",
                    Sourcecode: "2300JW",
                    CreatedOn: "2023-08-08T17:59:18Z",
                    LastDonationAmount: 0.0,
                    HighestDonationAmount: 0.0,
                    AverageDonationAmount: 0.0,
                    GiftAskLow: 10.0,
                    GiftAskMid: 15.0,
                    GiftAskHigh: 25.0,
                    JOMMobile: null,
                    LWCMobile: null,
                    DonorFrequency: "",
                    DonorType: "",
                    GivingHistory: [
                        {
                            Key: "2023",
                            Value: 0.0,
                        },
                    ],
                    AuthToken: null,
                    RedirectUrl: null,
                    DefaultCurrency: {
                        Id: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                        Name: "US Dollar",
                        Symbol: "$",
                        Iso3Code: "USD",
                        IsSelected: false,
                    },
                    AdminChurches: null,
                },
                CustomerId: "3302a646-1536-ee11-bdf4-000d3a190fe1",
                Payments: null,
                OrderItems: null,
                Status: 0,
                Discount: 0.0,
                Shipping: 0.0,
                ProductTotal: 10.0,
                DonationTotal: 0.0,
                EventTotal: 0.0,
                Subtotal: 0.0,
                Tax: 0.0,
                Total: 10.0,
                IsWebOrder: false,
                OrderDate: "2023-10-26T19:44:10",
                IsFromRecurringGift: false,
                OrderNumber: "ORD-4511938-J4C4M1",
                CurrencySymbol: "$",
                Currency: {
                    Id: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Name: "US Dollar",
                    Symbol: "$",
                    Iso3Code: "USD",
                    IsSelected: false,
                },
                StatusString: "0",
                TrackingNumbers: "",
            },
            {
                Id: "13cd23a9-5674-ee11-9ae7-000d3a190fe1",
                Contact: {
                    Id: "3302a646-1536-ee11-bdf4-000d3a190fe1",
                    IsLoggedIn: true,
                    IsGuest: false,
                    IsPartner: false,
                    Security: {
                        IsAdmin: false,
                        SecurityRoles: null,
                        SecurityFlags: null,
                        SecurityAuthority: null,
                    },
                    Address: {
                        Id: "b8063c8c-6264-4fec-aee0-238d9a8718f5",
                        CustomerId: null,
                        FirstName: "Don",
                        LastName: "Test",
                        IsPrimary: true,
                        IsDefaultBilling: false,
                        IsDefaultShipping: false,
                        IsSelected: false,
                        City: "INDIAN TRAIL",
                        StateDetail: {
                            Name: "North Carolina",
                            Iso2Code: "NC",
                            Country: null,
                            IsSelected: false,
                        },
                        DoNotMail: false,
                        State: "NC",
                        CountryDetail: {
                            Name: "UNITED STATES",
                            Iso2Code: "US",
                            Iso3Code: "USA",
                            IsSelected: false,
                            CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                            Id: "752029fe-6ea9-df11-9532-005056954cab",
                        },
                        Country: "UNITED STATES",
                        Summary:
                            "5507 Fulton Ridge Drive, Suite 4, INDIAN TRAIL, NC, 28079, UNITED STATES",
                        Latitude: 0.0,
                        Longitude: 0.0,
                        Line1: "5507 Fulton Ridge Drive",
                        Line2: "Suite 4",
                        Person: null,
                        Name: null,
                        PostalCode: "28079",
                        HasBasicData: true,
                    },
                    DefaultBillingAddress: {
                        Id: "8dde102e-8bf8-45d3-a0b1-00b5cb56a647",
                        CustomerId: null,
                        FirstName: "Don",
                        LastName: "Test",
                        IsPrimary: true,
                        IsDefaultBilling: false,
                        IsDefaultShipping: false,
                        IsSelected: false,
                        City: "INDIAN TRAIL",
                        StateDetail: {
                            Name: "North Carolina",
                            Iso2Code: "NC",
                            Country: null,
                            IsSelected: false,
                        },
                        DoNotMail: false,
                        State: "NC",
                        CountryDetail: {
                            Name: "UNITED STATES",
                            Iso2Code: "US",
                            Iso3Code: "USA",
                            IsSelected: false,
                            CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                            Id: "752029fe-6ea9-df11-9532-005056954cab",
                        },
                        Country: "UNITED STATES",
                        Summary:
                            "5507 Fulton Ridge Drive, Suite 4, INDIAN TRAIL, NC, 28079, UNITED STATES",
                        Latitude: 0.0,
                        Longitude: 0.0,
                        Line1: "5507 Fulton Ridge Drive",
                        Line2: "Suite 4",
                        Person: null,
                        Name: null,
                        PostalCode: "28079",
                        HasBasicData: true,
                    },
                    DefaultShippingAddress: {
                        Id: "67dd5c11-62a1-42e0-bc07-d62a63cdf671",
                        CustomerId: null,
                        FirstName: "Don",
                        LastName: "Test",
                        IsPrimary: true,
                        IsDefaultBilling: false,
                        IsDefaultShipping: false,
                        IsSelected: false,
                        City: "INDIAN TRAIL",
                        StateDetail: {
                            Name: "North Carolina",
                            Iso2Code: "NC",
                            Country: null,
                            IsSelected: false,
                        },
                        DoNotMail: false,
                        State: "NC",
                        CountryDetail: {
                            Name: "UNITED STATES",
                            Iso2Code: "US",
                            Iso3Code: "USA",
                            IsSelected: false,
                            CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                            Id: "752029fe-6ea9-df11-9532-005056954cab",
                        },
                        Country: "UNITED STATES",
                        Summary:
                            "5507 Fulton Ridge Drive, Suite 4, INDIAN TRAIL, NC, 28079, UNITED STATES",
                        Latitude: 0.0,
                        Longitude: 0.0,
                        Line1: "5507 Fulton Ridge Drive",
                        Line2: "Suite 4",
                        Person: null,
                        Name: null,
                        PostalCode: "28079",
                        HasBasicData: true,
                    },
                    BirthDate: null,
                    DoNotEmail: true,
                    DoNotPhone: true,
                    DoNotCallMobile: null,
                    AllowSMS: null,
                    DoNotPostalMail: false,
                    PrimaryEmailAddress: "ven-dobrien@lakewood.cc",
                    FirstName: "Don",
                    LastName: "Test",
                    FullName: "Don Test",
                    Gender: 3,
                    Acno: "C011006381",
                    Church: null,
                    Discount: 0.0,
                    PriceLevelId: "5f7fcdb8-a87a-e611-80c9-000d3a700f55",
                    Facebook: null,
                    Instagram: null,
                    TaxExempt: false,
                    Twitter: null,
                    LastLogin: "2023-10-30T18:29:25Z",
                    IsPrivate: false,
                    PhoneNumber: null,
                    MobilePhoneNumber: null,
                    SiteCode: "JOM",
                    Sourcecode: "2300JW",
                    CreatedOn: "2023-08-08T17:59:18Z",
                    LastDonationAmount: 0.0,
                    HighestDonationAmount: 0.0,
                    AverageDonationAmount: 0.0,
                    GiftAskLow: 10.0,
                    GiftAskMid: 15.0,
                    GiftAskHigh: 25.0,
                    JOMMobile: null,
                    LWCMobile: null,
                    DonorFrequency: "",
                    DonorType: "",
                    GivingHistory: [
                        {
                            Key: "2023",
                            Value: 0.0,
                        },
                    ],
                    AuthToken: null,
                    RedirectUrl: null,
                    DefaultCurrency: {
                        Id: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                        Name: "US Dollar",
                        Symbol: "$",
                        Iso3Code: "USD",
                        IsSelected: false,
                    },
                    AdminChurches: null,
                },
                CustomerId: "3302a646-1536-ee11-bdf4-000d3a190fe1",
                Payments: null,
                OrderItems: null,
                Status: 0,
                Discount: 0.0,
                Shipping: 0.0,
                ProductTotal: 5.0,
                DonationTotal: 0.0,
                EventTotal: 0.0,
                Subtotal: 0.0,
                Tax: 0.0,
                Total: 5.0,
                IsWebOrder: false,
                OrderDate: "2023-10-26T18:23:31",
                IsFromRecurringGift: false,
                OrderNumber: "ORD-4511937-V5H2J2",
                CurrencySymbol: "$",
                Currency: {
                    Id: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Name: "US Dollar",
                    Symbol: "$",
                    Iso3Code: "USD",
                    IsSelected: false,
                },
                StatusString: "0",
                TrackingNumbers: "",
            },
            {
                Id: "ce724c24-1774-ee11-9ae7-002248249872",
                Contact: {
                    Id: "3302a646-1536-ee11-bdf4-000d3a190fe1",
                    IsLoggedIn: true,
                    IsGuest: false,
                    IsPartner: false,
                    Security: {
                        IsAdmin: false,
                        SecurityRoles: null,
                        SecurityFlags: null,
                        SecurityAuthority: null,
                    },
                    Address: {
                        Id: "b8063c8c-6264-4fec-aee0-238d9a8718f5",
                        CustomerId: null,
                        FirstName: "Don",
                        LastName: "Test",
                        IsPrimary: true,
                        IsDefaultBilling: false,
                        IsDefaultShipping: false,
                        IsSelected: false,
                        City: "INDIAN TRAIL",
                        StateDetail: {
                            Name: "North Carolina",
                            Iso2Code: "NC",
                            Country: null,
                            IsSelected: false,
                        },
                        DoNotMail: false,
                        State: "NC",
                        CountryDetail: {
                            Name: "UNITED STATES",
                            Iso2Code: "US",
                            Iso3Code: "USA",
                            IsSelected: false,
                            CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                            Id: "752029fe-6ea9-df11-9532-005056954cab",
                        },
                        Country: "UNITED STATES",
                        Summary:
                            "5507 Fulton Ridge Drive, Suite 4, INDIAN TRAIL, NC, 28079, UNITED STATES",
                        Latitude: 0.0,
                        Longitude: 0.0,
                        Line1: "5507 Fulton Ridge Drive",
                        Line2: "Suite 4",
                        Person: null,
                        Name: null,
                        PostalCode: "28079",
                        HasBasicData: true,
                    },
                    DefaultBillingAddress: {
                        Id: "8dde102e-8bf8-45d3-a0b1-00b5cb56a647",
                        CustomerId: null,
                        FirstName: "Don",
                        LastName: "Test",
                        IsPrimary: true,
                        IsDefaultBilling: false,
                        IsDefaultShipping: false,
                        IsSelected: false,
                        City: "INDIAN TRAIL",
                        StateDetail: {
                            Name: "North Carolina",
                            Iso2Code: "NC",
                            Country: null,
                            IsSelected: false,
                        },
                        DoNotMail: false,
                        State: "NC",
                        CountryDetail: {
                            Name: "UNITED STATES",
                            Iso2Code: "US",
                            Iso3Code: "USA",
                            IsSelected: false,
                            CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                            Id: "752029fe-6ea9-df11-9532-005056954cab",
                        },
                        Country: "UNITED STATES",
                        Summary:
                            "5507 Fulton Ridge Drive, Suite 4, INDIAN TRAIL, NC, 28079, UNITED STATES",
                        Latitude: 0.0,
                        Longitude: 0.0,
                        Line1: "5507 Fulton Ridge Drive",
                        Line2: "Suite 4",
                        Person: null,
                        Name: null,
                        PostalCode: "28079",
                        HasBasicData: true,
                    },
                    DefaultShippingAddress: {
                        Id: "67dd5c11-62a1-42e0-bc07-d62a63cdf671",
                        CustomerId: null,
                        FirstName: "Don",
                        LastName: "Test",
                        IsPrimary: true,
                        IsDefaultBilling: false,
                        IsDefaultShipping: false,
                        IsSelected: false,
                        City: "INDIAN TRAIL",
                        StateDetail: {
                            Name: "North Carolina",
                            Iso2Code: "NC",
                            Country: null,
                            IsSelected: false,
                        },
                        DoNotMail: false,
                        State: "NC",
                        CountryDetail: {
                            Name: "UNITED STATES",
                            Iso2Code: "US",
                            Iso3Code: "USA",
                            IsSelected: false,
                            CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                            Id: "752029fe-6ea9-df11-9532-005056954cab",
                        },
                        Country: "UNITED STATES",
                        Summary:
                            "5507 Fulton Ridge Drive, Suite 4, INDIAN TRAIL, NC, 28079, UNITED STATES",
                        Latitude: 0.0,
                        Longitude: 0.0,
                        Line1: "5507 Fulton Ridge Drive",
                        Line2: "Suite 4",
                        Person: null,
                        Name: null,
                        PostalCode: "28079",
                        HasBasicData: true,
                    },
                    BirthDate: null,
                    DoNotEmail: true,
                    DoNotPhone: true,
                    DoNotCallMobile: null,
                    AllowSMS: null,
                    DoNotPostalMail: false,
                    PrimaryEmailAddress: "ven-dobrien@lakewood.cc",
                    FirstName: "Don",
                    LastName: "Test",
                    FullName: "Don Test",
                    Gender: 3,
                    Acno: "C011006381",
                    Church: null,
                    Discount: 0.0,
                    PriceLevelId: "5f7fcdb8-a87a-e611-80c9-000d3a700f55",
                    Facebook: null,
                    Instagram: null,
                    TaxExempt: false,
                    Twitter: null,
                    LastLogin: "2023-10-30T18:29:25Z",
                    IsPrivate: false,
                    PhoneNumber: null,
                    MobilePhoneNumber: null,
                    SiteCode: "JOM",
                    Sourcecode: "2300JW",
                    CreatedOn: "2023-08-08T17:59:18Z",
                    LastDonationAmount: 0.0,
                    HighestDonationAmount: 0.0,
                    AverageDonationAmount: 0.0,
                    GiftAskLow: 10.0,
                    GiftAskMid: 15.0,
                    GiftAskHigh: 25.0,
                    JOMMobile: null,
                    LWCMobile: null,
                    DonorFrequency: "",
                    DonorType: "",
                    GivingHistory: [
                        {
                            Key: "2023",
                            Value: 0.0,
                        },
                    ],
                    AuthToken: null,
                    RedirectUrl: null,
                    DefaultCurrency: {
                        Id: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                        Name: "US Dollar",
                        Symbol: "$",
                        Iso3Code: "USD",
                        IsSelected: false,
                    },
                    AdminChurches: null,
                },
                CustomerId: "3302a646-1536-ee11-bdf4-000d3a190fe1",
                Payments: null,
                OrderItems: null,
                Status: 1,
                Discount: 0.0,
                Shipping: 0.0,
                ProductTotal: 15.0,
                DonationTotal: 0.0,
                EventTotal: 0.0,
                Subtotal: 0.0,
                Tax: 0.0,
                Total: 15.0,
                IsWebOrder: false,
                OrderDate: "2023-10-26T10:48:47",
                IsFromRecurringGift: false,
                OrderNumber: "ORD-4511936-C6T2H5",
                CurrencySymbol: "$",
                Currency: {
                    Id: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Name: "US Dollar",
                    Symbol: "$",
                    Iso3Code: "USD",
                    IsSelected: false,
                },
                StatusString: "Processing",
                TrackingNumbers: "",
            },
        ],
    })
);

export const SPOOFED_GET_OrderDetails: IOrderDetailsAPIResult = JSON.parse(
    JSON.stringify({
        results: {
            Id: "a82365fe-6274-ee11-9ae7-000d3a18283a",
            Contact: {
                Id: "3302a646-1536-ee11-bdf4-000d3a190fe1",
                IsLoggedIn: true,
                IsGuest: false,
                IsPartner: false,
                Security: {
                    IsAdmin: false,
                    SecurityRoles: null,
                    SecurityFlags: null,
                    SecurityAuthority: null,
                },
                Address: {
                    Id: "b8063c8c-6264-4fec-aee0-238d9a8718f5",
                    CustomerId: null,
                    FirstName: "Don",
                    LastName: "Test",
                    IsPrimary: true,
                    IsDefaultBilling: false,
                    IsDefaultShipping: false,
                    IsSelected: false,
                    City: "INDIAN TRAIL",
                    StateDetail: {
                        Name: "North Carolina",
                        Iso2Code: "NC",
                        Country: null,
                        IsSelected: false,
                    },
                    DoNotMail: false,
                    State: "NC",
                    CountryDetail: {
                        Name: "UNITED STATES",
                        Iso2Code: "US",
                        Iso3Code: "USA",
                        IsSelected: false,
                        CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                        Id: "752029fe-6ea9-df11-9532-005056954cab",
                    },
                    Country: "UNITED STATES",
                    Summary:
                        "5507 Fulton Ridge Drive, Suite 4, INDIAN TRAIL, NC, 28079, UNITED STATES",
                    Latitude: 0.0,
                    Longitude: 0.0,
                    Line1: "5507 Fulton Ridge Drive",
                    Line2: "Suite 4",
                    Person: null,
                    Name: null,
                    PostalCode: "28079",
                    HasBasicData: true,
                },
                DefaultBillingAddress: {
                    Id: "8dde102e-8bf8-45d3-a0b1-00b5cb56a647",
                    CustomerId: null,
                    FirstName: "Don",
                    LastName: "Test",
                    IsPrimary: true,
                    IsDefaultBilling: false,
                    IsDefaultShipping: false,
                    IsSelected: false,
                    City: "INDIAN TRAIL",
                    StateDetail: {
                        Name: "North Carolina",
                        Iso2Code: "NC",
                        Country: null,
                        IsSelected: false,
                    },
                    DoNotMail: false,
                    State: "NC",
                    CountryDetail: {
                        Name: "UNITED STATES",
                        Iso2Code: "US",
                        Iso3Code: "USA",
                        IsSelected: false,
                        CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                        Id: "752029fe-6ea9-df11-9532-005056954cab",
                    },
                    Country: "UNITED STATES",
                    Summary:
                        "5507 Fulton Ridge Drive, Suite 4, INDIAN TRAIL, NC, 28079, UNITED STATES",
                    Latitude: 0.0,
                    Longitude: 0.0,
                    Line1: "5507 Fulton Ridge Drive",
                    Line2: "Suite 4",
                    Person: null,
                    Name: null,
                    PostalCode: "28079",
                    HasBasicData: true,
                },
                DefaultShippingAddress: {
                    Id: "67dd5c11-62a1-42e0-bc07-d62a63cdf671",
                    CustomerId: null,
                    FirstName: "Don",
                    LastName: "Test",
                    IsPrimary: true,
                    IsDefaultBilling: false,
                    IsDefaultShipping: false,
                    IsSelected: false,
                    City: "INDIAN TRAIL",
                    StateDetail: {
                        Name: "North Carolina",
                        Iso2Code: "NC",
                        Country: null,
                        IsSelected: false,
                    },
                    DoNotMail: false,
                    State: "NC",
                    CountryDetail: {
                        Name: "UNITED STATES",
                        Iso2Code: "US",
                        Iso3Code: "USA",
                        IsSelected: false,
                        CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                        Id: "752029fe-6ea9-df11-9532-005056954cab",
                    },
                    Country: "UNITED STATES",
                    Summary:
                        "5507 Fulton Ridge Drive, Suite 4, INDIAN TRAIL, NC, 28079, UNITED STATES",
                    Latitude: 0.0,
                    Longitude: 0.0,
                    Line1: "5507 Fulton Ridge Drive",
                    Line2: "Suite 4",
                    Person: null,
                    Name: null,
                    PostalCode: "28079",
                    HasBasicData: true,
                },
                BirthDate: null,
                DoNotEmail: true,
                DoNotPhone: true,
                DoNotCallMobile: null,
                AllowSMS: null,
                DoNotPostalMail: false,
                PrimaryEmailAddress: "ven-dobrien@lakewood.cc",
                FirstName: "Don",
                LastName: "Test",
                FullName: "Don Test",
                Gender: 3,
                Acno: "C011006381",
                Church: null,
                Discount: 0.0,
                PriceLevelId: "5f7fcdb8-a87a-e611-80c9-000d3a700f55",
                Facebook: null,
                Instagram: null,
                TaxExempt: false,
                Twitter: null,
                LastLogin: "2023-10-30T18:29:25Z",
                IsPrivate: false,
                PhoneNumber: null,
                MobilePhoneNumber: null,
                SiteCode: "JOM",
                Sourcecode: "2300JW",
                CreatedOn: "2023-08-08T17:59:18Z",
                LastDonationAmount: 0.0,
                HighestDonationAmount: 0.0,
                AverageDonationAmount: 0.0,
                GiftAskLow: 10.0,
                GiftAskMid: 15.0,
                GiftAskHigh: 25.0,
                JOMMobile: null,
                LWCMobile: null,
                DonorFrequency: "",
                DonorType: "",
                GivingHistory: [
                    {
                        Key: "2023",
                        Value: 0.0,
                    },
                ],
                AuthToken: null,
                RedirectUrl: null,
                DefaultCurrency: {
                    Id: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                    Name: "US Dollar",
                    Symbol: "$",
                    Iso3Code: "USD",
                    IsSelected: false,
                },
                AdminChurches: null,
            },
            CustomerId: "3302a646-1536-ee11-bdf4-000d3a190fe1",
            Payments: [
                {
                    Id: "b6be9004-6374-ee11-9ae7-000d3a57ac5f",
                    Method: {
                        Id: "246d02d7-6274-ee11-9ae7-002248249872",
                        Alias: "EFT",
                        NameOnAccount: null,
                        IsSelected: true,
                        CardType: null,
                        CardExpMMYY: null,
                        CardToken: "246d02d7-6274-ee11-9ae7-002248249872",
                        MaskedCardNumber: null,
                        BankAccountNumber: "1234567891234",
                        Type: 2,
                        BankRoutingNumber: "123456780",
                        BankAccountId: "246d02d7-6274-ee11-9ae7-002248249872",
                        Code: null,
                        Company: null,
                        CustomerId: null,
                        DigitalWalletName: null,
                        Summary: "Savings",
                        HasRequiredDetails: false,
                    },
                    AuthorizationToken: null,
                    ConfirmationToken: null,
                    Amount: 25.0,
                    Currency: {
                        Id: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                        Name: "US Dollar",
                        Symbol: "$",
                        Iso3Code: "USD",
                        IsSelected: false,
                    },
                    HasRequiredDetailsForRecurringDonationOnly: false,
                    HasRequiredDetails: false,
                },
            ],
            OrderItems: [
                {
                    Id: "6026cc04-6374-ee11-9ae7-0022482497d6",
                    Shipping: {
                        Method: {
                            Name: "UMI",
                            FOB: "UMD",
                            EstimatedDelivery: "5 - 15 Business Days",
                            Id: "00000000-0000-0000-0000-000000000000",
                            Classification: "Economy",
                        },
                        Amount: 0.0,
                        Warehouse: {
                            Id: "0f2005e3-e50d-e211-9dde-005056810022",
                            Name: "PBD",
                            Country: {
                                Name: "UNITED STATES",
                                Iso2Code: "US",
                                Iso3Code: "USA",
                                IsSelected: false,
                                CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                                Id: "752029fe-6ea9-df11-9532-005056954cab",
                            },
                            Priorities: [
                                {
                                    Priority: 1,
                                    CurrencyISO3: "CAD",
                                },
                                {
                                    Priority: 2,
                                    CurrencyISO3: "GBP",
                                },
                                {
                                    Priority: 1,
                                    CurrencyISO3: "CAD",
                                },
                                {
                                    Priority: 2,
                                    CurrencyISO3: "USD",
                                },
                            ],
                        },
                        IsDefault: false,
                        PackDate: null,
                        ShipDate: null,
                        TrackingNumber: "",
                    },
                    Quantity: 1,
                    Product: {
                        Id: "c071eb25-e722-ed11-80f4-000d3a7075d4",
                        DisplayOrder: null,
                        CreatedOn: "2022-08-23T13:26:15Z",
                        ModifedOn: "2022-10-07T20:09:42Z",
                        StartDate: null,
                        EndDate: null,
                        Name: "Audiobook-Your Greater Is Coming",
                        IsDonation: false,
                        Description:
                            "Releases October 4, 2022\nWhether you’re climbing toward the next level, stretching for an out-of-reach goal, or doing your utmost to overcome a challenge, it’s time to step into a better life filled with more. When your patience strains to meet your expectations, you have to remember that where you are now is not where you’re about to be!\n                                                     \nIn Your Greater Is Coming, #1 New York Times bestselling author Joel Osteen challenges your perception of your present situation and inspires you to persevere for the best that’s just ahead. Whatever you’re experiencing, don’t lose faith or give up on your dreams. Wait for your greater, because your greater is coming—greater joy, greater strength, greater relationships. Greater opportunities, greater success, and greater peace are all yours. Whatever you’ve been waiting for, working for, praying for, and hoping for is on the way. \n \nYour Greater Is Coming will nourish your soul and empower your heart to push through pain and master the mundane. Your story is far from over, and the best is yet to come.  Don’t give up just as you’re about to discover a new level of increase, ease, and joy. Glimpse your breakthrough just ahead and hold on just a little longer—your greater is coming!",
                        SEODescription: null,
                        SEOKeywords: null,
                        Topics: [],
                        SKU: "JCB0104E",
                        AuthorOrProducer: "Joel Osteen",
                        Weight: 0.0,
                        AvailableQuantity: 0,
                        AreBackordersAllowed: true,
                        IsBackordered: true,
                        BackorderExpectedDate: null,
                        Detail1: "Audiobook",
                        Detail2: "10/4/2022",
                        Images: [
                            {
                                Id: "ce18f010-ea22-ed11-80f4-000d3a7075d4",
                                Type: 5,
                            },
                            {
                                Id: "3d79ef16-ea22-ed11-80f4-000d3a7075d4",
                                Type: 4,
                            },
                            {
                                Id: "8550f522-ea22-ed11-80f4-000d3a7075d4",
                                Type: 3,
                            },
                            {
                                Id: "f23bfd2e-ea22-ed11-80f4-000d3a7075d4",
                                Type: 6,
                            },
                            {
                                Id: "036ef13a-ea22-ed11-80f4-000d3a7075d4",
                                Type: 2,
                            },
                        ],
                        IsOnSale: true,
                        IsNew: true,
                        IsFeatured: true,
                        IsPreorder: false,
                        IsDiscountAllowed: false,
                        AreInstallmentsAllowed: false,
                        Price: 25.0,
                        MSRP: 35.0,
                        IsDownloadable: false,
                        DownloadURL: null,
                        VariantGroup: null,
                        VariantProducts: null,
                        Variants: [],
                        Tags: [],
                        RelatedProducts: [
                            {
                                Id: "b1fd6564-2272-e711-927b-000d3a700740",
                                DisplayOrder: null,
                                CreatedOn: "2017-07-26T16:49:32Z",
                                ModifedOn: "2022-10-09T14:14:11Z",
                                StartDate: null,
                                EndDate: "2017-07-25T16:50:42Z",
                                Name: "All Things Are Working for Your Good (formerly Blessed in the Darkness)",
                                IsDonation: false,
                                Description:
                                    "All of us will go through dark times that we don't understand: a difficulty with a friend, an unfair situation at work, a financial setback, an unexpected illness, a divorce, or the loss of a loved one. Those types of experiences are part of the human journey. But when we find ourselves in such a place, it's important that we keep a positive perspective. \n\nIn his new book, Joel encourages us to keep the right perspective even in the difficult times. We shouldn’t have to just go through the challenge, but grow through them, knowing that they’re all working for your good. Through practical applications and scriptural insight, Blessed in the Darkness focuses on how to draw closer to God and trust Him when life doesn't make sense.",
                                SEODescription: null,
                                SEOKeywords: null,
                                Topics: [],
                                SKU: "JCB0073E",
                                AuthorOrProducer: "Joel Osteen",
                                Weight: 5.3,
                                AvailableQuantity: 0,
                                AreBackordersAllowed: true,
                                IsBackordered: true,
                                BackorderExpectedDate: null,
                                Detail1: "Audiobook",
                                Detail2: "10/24/17",
                                Images: [],
                                IsOnSale: false,
                                IsNew: false,
                                IsFeatured: false,
                                IsPreorder: false,
                                IsDiscountAllowed: true,
                                AreInstallmentsAllowed: false,
                                Price: 9.99,
                                MSRP: 30.0,
                                IsDownloadable: false,
                                DownloadURL: null,
                                VariantGroup: null,
                                VariantProducts: null,
                                Variants: [],
                                Tags: [],
                                RelatedProducts: [],
                                Warehouses: [],
                                Type: "Product",
                                CurrentCategory: null,
                                NextProduct: null,
                                PrevProduct: null,
                                IsQualifyingBook: false,
                                IsQualifyingAudioBook: true,
                                DefaultUoMId: "675505b8-9b2a-4075-951a-af59ecbeff6f",
                                IsBundle: false,
                                BundledProducts: null,
                                IsQualifyBookOrQualifyingAudioBook: true,
                            },
                            {
                                Id: "b50d80bc-8457-ec11-80ec-000d3a700f55",
                                DisplayOrder: null,
                                CreatedOn: "2021-12-07T17:40:18Z",
                                ModifedOn: "2022-03-01T15:05:18Z",
                                StartDate: null,
                                EndDate: null,
                                Name: "Audiobook-Rule Your Day",
                                IsDonation: false,
                                Description:
                                    "You would like to savor each moment, grow into your best life, engage in productive relationships, and see your dreams come to pass. But distractions, delays, and disappointments relentlessly hijack your plans and undermine your good intentions. While you can’t control everything that comes your way, you can control how life’s unexpected setbacks affect your attitude, emotions, thoughts, and actions.\n\nIn his latest work, #1New York Times bestselling author Joel Osteen shows you how to be intentional and Rule Your Day. With his trademark wisdom and unwavering positivity, Joel reveals six keys for claiming control over each new day. He teaches you how to identify faulty thinking, recast your vision for the future, rise above your circumstances, guard your heart and mind against negativity, and transcend distractions to focus on what matters most.\n\nWhen you work with the tools God has given you and take control of your time, you can bounce back from disappointments, prevent poisonous thoughts from entering your atmosphere, and fully enjoy the bright future that’s ahead of you. Don’t settle for surviving when you could be thriving—Rule Your Day!",
                                SEODescription: null,
                                SEOKeywords: null,
                                Topics: [],
                                SKU: "JCB0099E",
                                AuthorOrProducer: "Joel Osteen",
                                Weight: 0.0,
                                AvailableQuantity: 0,
                                AreBackordersAllowed: true,
                                IsBackordered: true,
                                BackorderExpectedDate: null,
                                Detail1: "Audiobook",
                                Detail2: "03/08/2022",
                                Images: [],
                                IsOnSale: false,
                                IsNew: true,
                                IsFeatured: true,
                                IsPreorder: true,
                                IsDiscountAllowed: false,
                                AreInstallmentsAllowed: false,
                                Price: 25.0,
                                MSRP: 35.0,
                                IsDownloadable: false,
                                DownloadURL: null,
                                VariantGroup: null,
                                VariantProducts: null,
                                Variants: [],
                                Tags: [],
                                RelatedProducts: [],
                                Warehouses: [],
                                Type: "Product",
                                CurrentCategory: null,
                                NextProduct: null,
                                PrevProduct: null,
                                IsQualifyingBook: false,
                                IsQualifyingAudioBook: true,
                                DefaultUoMId: "675505b8-9b2a-4075-951a-af59ecbeff6f",
                                IsBundle: false,
                                BundledProducts: null,
                                IsQualifyBookOrQualifyingAudioBook: true,
                            },
                            {
                                Id: "ab7bd0bb-5662-eb11-80f1-000d3a7075d4",
                                DisplayOrder: null,
                                CreatedOn: "2021-01-29T17:23:45Z",
                                ModifedOn: "2021-09-20T20:20:09Z",
                                StartDate: null,
                                EndDate: null,
                                Name: "Peaceful on Purpose: The Power to Remain Calm, Strong, and Confident in Every Season",
                                IsDonation: false,
                                Description:
                                    "Live from a place of abundant peace in the midst of life's everyday worries and\nstress with #1 New York Times bestselling author and Lakewood Church\npastor Joel Osteen.\nThe opposite of peace is worry and stress. Both are thieves that rob you of your\nsleep, joy, creativity, and good decisions. If you allow them into your mind, they can\neven can even keep you from your destiny. But if you learn how to change your\nautomatic responses to these struggles and give your problems to God, He can go to\nwork in your life.\nIf you're tired of living in tension and anxiety, then it's time to change. In Peaceful on\nPurpose, you will discover that you weren't designed to carry the heavy load yourself:\nstep back to let God step in. Find peace so that you can stop worrying about your\nhealth, job, finances, or relationships.\nLife may be chaotic all around you, but you can live grounded in a calm spirit by\ndrawing on scriptural examples and Joel's insightful personal experiences to find\nfulfillment. Learn how to give it to God so that He can exceed your expectations.",
                                SEODescription: null,
                                SEOKeywords: null,
                                Topics: [],
                                SKU: "JCB0092E",
                                AuthorOrProducer: "Joel Osteen",
                                Weight: 5.5,
                                AvailableQuantity: 0,
                                AreBackordersAllowed: false,
                                IsBackordered: true,
                                BackorderExpectedDate: null,
                                Detail1: "Audiobook",
                                Detail2: "5/16/21",
                                Images: [],
                                IsOnSale: false,
                                IsNew: false,
                                IsFeatured: false,
                                IsPreorder: false,
                                IsDiscountAllowed: true,
                                AreInstallmentsAllowed: false,
                                Price: 21.0,
                                MSRP: 30.0,
                                IsDownloadable: false,
                                DownloadURL: null,
                                VariantGroup: null,
                                VariantProducts: null,
                                Variants: [],
                                Tags: [],
                                RelatedProducts: [],
                                Warehouses: [],
                                Type: "Product",
                                CurrentCategory: null,
                                NextProduct: null,
                                PrevProduct: null,
                                IsQualifyingBook: false,
                                IsQualifyingAudioBook: true,
                                DefaultUoMId: "675505b8-9b2a-4075-951a-af59ecbeff6f",
                                IsBundle: false,
                                BundledProducts: null,
                                IsQualifyBookOrQualifyingAudioBook: true,
                            },
                        ],
                        Warehouses: [
                            {
                                Id: "0f2005e3-e50d-e211-9dde-005056810022",
                                Name: "PBD",
                                Country: {
                                    Name: "UNITED STATES",
                                    Iso2Code: "US",
                                    Iso3Code: "USA",
                                    IsSelected: false,
                                    CurrencyId: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                                    Id: "752029fe-6ea9-df11-9532-005056954cab",
                                },
                                Priorities: [
                                    {
                                        Priority: 1,
                                        CurrencyISO3: "CAD",
                                    },
                                    {
                                        Priority: 2,
                                        CurrencyISO3: "GBP",
                                    },
                                    {
                                        Priority: 1,
                                        CurrencyISO3: "CAD",
                                    },
                                    {
                                        Priority: 2,
                                        CurrencyISO3: "USD",
                                    },
                                ],
                            },
                        ],
                        Type: "Product",
                        CurrentCategory: null,
                        NextProduct: null,
                        PrevProduct: null,
                        IsQualifyingBook: false,
                        IsQualifyingAudioBook: true,
                        DefaultUoMId: "675505b8-9b2a-4075-951a-af59ecbeff6f",
                        IsBundle: false,
                        BundledProducts: null,
                        IsQualifyBookOrQualifyingAudioBook: true,
                    },
                    IsPromoItem: false,
                    Amount: 25.0,
                    Notes: [],
                    Total: 0.0,
                    Warehouse: null,
                },
            ],
            Status: 1,
            Discount: 0.0,
            Shipping: 0.0,
            ProductTotal: 25.0,
            DonationTotal: 0.0,
            EventTotal: 0.0,
            Subtotal: 25.0,
            Tax: 0.0,
            Total: 25.0,
            IsWebOrder: true,
            OrderDate: "2023-10-26T19:51:52",
            IsFromRecurringGift: false,
            OrderNumber: "ORD-4511940-S8R4F9",
            CurrencySymbol: "$",
            Currency: {
                Id: "2910ccf8-ec75-e611-80ca-000d3a7075d4",
                Name: "US Dollar",
                Symbol: "$",
                Iso3Code: "USD",
                IsSelected: false,
            },
            StatusString: "Processing",
            TrackingNumbers: "",
        },
    })
);
